# _config.yml
title: "我的博客"
description: "记录技术与生活"
url: "https://aozijx.github.io/xuao"

# 基础设置
timezone: ""
encoding: utf-8

# 主题（需安装或通过 GitHub Pages 支持）
theme: 

# 自定义数据
author: "Hiner"
email: "xxhtxml@outlook.com"
github: "https://github.com/aozijx"